apiVersion: apps/v1
kind: Deployment
metadata:
  name: isolated-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: isolated-controller
  template:
    metadata:
      labels:
        name: isolated-controller
    spec:
      serviceAccountName: isolated-controller
      containers:
        - name: isolated-controller
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - isolated-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "isolated-controller"
